name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/composer.lock') }}

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          touch database/database.sqlite
          php artisan key:generate
          php artisan migrate
          
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
          # Optional: Ignore warnings
          php_codesniffer_args: "-n"

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
